<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Méndez">

<title>Cuando los leads mezclan efectos pos-tratamiento: contaminación dinámica en event studies TWFE – Daniel Méndez</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6b423f165eeea3787de40cb4f8e821c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="robots" content="noindex, nofollow">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="../../econometria/assets/portfolio.css">
<link rel="stylesheet" href="../../econometria/assets/t01_palette.css">
<link rel="stylesheet" href="../../assets/analysis-layout.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Daniel Méndez</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../problemas-negocio.html"> 
<span class="menu-text">Problemas de negocio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../econometria/index.html"> 
<span class="menu-text">Econometría</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../causalidad/index.html"> 
<span class="menu-text">Causalidad</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../machine-learning/index.html"> 
<span class="menu-text">Machine Learning</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../sobre-mi.html"> 
<span class="menu-text">Sobre mí</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#pregunta-central" id="toc-pregunta-central" class="nav-link active" data-scroll-target="#pregunta-central">Pregunta central</a></li>
  <li><a href="#la-promesa-visual-de-un-event-study" id="toc-la-promesa-visual-de-un-event-study" class="nav-link" data-scroll-target="#la-promesa-visual-de-un-event-study">La promesa visual de un event study</a></li>
  <li><a href="#por-qué-una-etiqueta-temporal-no-define-el-estimando" id="toc-por-qué-una-etiqueta-temporal-no-define-el-estimando" class="nav-link" data-scroll-target="#por-qué-una-etiqueta-temporal-no-define-el-estimando">Por qué una etiqueta temporal no define el estimando</a></li>
  <li><a href="#cuando-un-lead-incorpora-efectos-posteriores" id="toc-cuando-un-lead-incorpora-efectos-posteriores" class="nav-link" data-scroll-target="#cuando-un-lead-incorpora-efectos-posteriores">Cuando un lead incorpora efectos posteriores</a></li>
  <li><a href="#ausencia-de-anticipación-no-garantiza-leads-twfe-iguales-a-cero" id="toc-ausencia-de-anticipación-no-garantiza-leads-twfe-iguales-a-cero" class="nav-link" data-scroll-target="#ausencia-de-anticipación-no-garantiza-leads-twfe-iguales-a-cero">Ausencia de anticipación no garantiza leads TWFE iguales a cero</a></li>
  <li><a href="#aplicación-hospitalización-y-consecuencias-económicas" id="toc-aplicación-hospitalización-y-consecuencias-económicas" class="nav-link" data-scroll-target="#aplicación-hospitalización-y-consecuencias-económicas">Aplicación: hospitalización y consecuencias económicas</a></li>
  <li><a href="#cohortes-control-y-soporte" id="toc-cohortes-control-y-soporte" class="nav-link" data-scroll-target="#cohortes-control-y-soporte">Cohortes, control y soporte</a></li>
  <li><a href="#twfe-frente-a-interaction-weighted" id="toc-twfe-frente-a-interaction-weighted" class="nav-link" data-scroll-target="#twfe-frente-a-interaction-weighted">TWFE frente a interaction-weighted</a></li>
  <li><a href="#gasto-médico-e-ingresos-laborales" id="toc-gasto-médico-e-ingresos-laborales" class="nav-link" data-scroll-target="#gasto-médico-e-ingresos-laborales">Gasto médico e ingresos laborales</a></li>
  <li><a href="#qué-dicen-y-qué-no-dicen-los-leads" id="toc-qué-dicen-y-qué-no-dicen-los-leads" class="nav-link" data-scroll-target="#qué-dicen-y-qué-no-dicen-los-leads">Qué dicen —y qué no dicen— los leads</a></li>
  <li><a href="#sensibilidad-con-covariables-prefijadas" id="toc-sensibilidad-con-covariables-prefijadas" class="nav-link" data-scroll-target="#sensibilidad-con-covariables-prefijadas">Sensibilidad con covariables prefijadas</a></li>
  <li><a href="#qué-exige-una-dinámica-causal-interpretable" id="toc-qué-exige-una-dinámica-causal-interpretable" class="nav-link" data-scroll-target="#qué-exige-una-dinámica-causal-interpretable">Qué exige una dinámica causal interpretable</a></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión">Conclusión</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cuando los leads mezclan efectos pos-tratamiento: contaminación dinámica en event studies TWFE</h1>
<p class="subtitle lead">Por qué una etiqueta temporal no basta para interpretar una trayectoria causal bajo adopción escalonada</p>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel Méndez </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">9 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="../../causalidad/did-moderno/index.html">← Volver a Difference-in-Differences moderno</a></p>
<div class="hero-box">
<div class="hero-title">
<p>Un coeficiente llamado “lead −2” puede contener efectos posteriores al tratamiento</p>
</div>
<div class="hero-sub">
<p>Los event studies TWFE parecen ordenar el tiempo con claridad: leads antes, una referencia y lags después. Con adopción escalonada y efectos heterogéneos, esa etiqueta no determina por sí sola qué efectos causales agrega cada coeficiente.</p>
</div>
</div>
<section id="pregunta-central" class="level2">
<h2 class="anchored" data-anchor-id="pregunta-central">Pregunta central</h2>
<p>¿Los coeficientes de un event study TWFE miden realmente el efecto causal correspondiente a cada período relativo al tratamiento?</p>
<p><strong>Respuesta corta:</strong> no necesariamente. Cada coeficiente puede combinar efectos de distintas cohortes y otros tiempos relativos. Incluso un <em>lead</em> puede asignar peso a efectos pos-tratamiento y desplazarse aunque no exista anticipación causal verdadera.</p>
</section>
<section id="la-promesa-visual-de-un-event-study" class="level2">
<h2 class="anchored" data-anchor-id="la-promesa-visual-de-un-event-study">La promesa visual de un event study</h2>
<p>La lectura habitual es atractiva: los <em>leads</em> describen la evolución previa, el período omitido fija la referencia y los <em>lags</em> reconstruyen cómo cambia el efecto después del tratamiento. Bajo un único momento de adopción y efectos homogéneos, esa intuición puede ser adecuada.</p>
<p>Con adopción escalonada, cada punto de la trayectoria surge de comparar cohortes expuestas en momentos diferentes. Si los efectos también varían entre cohortes o con la duración de la exposición, una regresión TWFE dinámica no recupera automáticamente un ATT limpio para cada tiempo relativo.</p>
</section>
<section id="por-qué-una-etiqueta-temporal-no-define-el-estimando" class="level2">
<h2 class="anchored" data-anchor-id="por-qué-una-etiqueta-temporal-no-define-el-estimando">Por qué una etiqueta temporal no define el estimando</h2>
<p>El efecto medio sobre los tratados de la cohorte <span class="math inline">\(e\)</span> en el tiempo relativo <span class="math inline">\(k\)</span> se denota <span class="math inline">\(CATT_{e,k}\)</span>. Bajo los supuestos de identificación y la normalización de referencia, el coeficiente poblacional TWFE asociado con <span class="math inline">\(\ell\)</span> puede representarse esquemáticamente como una combinación de esos efectos:</p>
<p><span class="math display">\[
\mu_{\ell}^{TWFE}
=\sum_{e,k} w_{e,k}^{\ell}\,CATT_{e,k}.
\]</span></p>
<p>El superíndice <span class="math inline">\(\ell\)</span> identifica el coeficiente de la regresión. El subíndice <span class="math inline">\(k\)</span> identifica el tiempo relativo del efecto que recibe peso. Nada obliga a que <span class="math inline">\(k=\ell\)</span> en todas las celdas. Esa diferencia es el origen de la contaminación dinámica.</p>
<p>El análisis anterior mostró que TWFE puede ponderar de manera problemática efectos heterogéneos en un coeficiente estático. Aquí el mismo problema se extiende a una secuencia completa de <em>leads</em> y <em>lags</em>.</p>
</section>
<section id="cuando-un-lead-incorpora-efectos-posteriores" class="level2">
<h2 class="anchored" data-anchor-id="cuando-un-lead-incorpora-efectos-posteriores">Cuando un lead incorpora efectos posteriores</h2>
<p>El diagnóstico del coeficiente <code>lead −2</code> revela pesos distintos de cero sobre efectos ocurridos en los períodos 0 y 1 de varias cohortes. Esos efectos pertenecen al pos-tratamiento, aunque el coeficiente visible esté etiquetado como previo.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_m06_lead_menos2_contaminacion.svg" class="img-fluid figure-img" alt="El coeficiente TWFE etiquetado como lead menos dos asigna pesos positivos y negativos a celdas pos-tratamiento de las cohortes 8, 9 y 10 en los tiempos relativos cero y uno. Por tanto, no utiliza exclusivamente información del período menos dos."></p>
<figcaption>Contaminación pos-tratamiento del coeficiente lead menos dos</figcaption>
</figure>
</div>
<p>La suma de esos pesos sobre períodos posteriores puede ser pequeña o incluso cercana a cero. Eso no implica que su contribución sea nula: al multiplicarlos por efectos heterogéneos de distinta magnitud, las cancelaciones de pesos dejan de garantizar cancelaciones económicas.</p>
</section>
<section id="ausencia-de-anticipación-no-garantiza-leads-twfe-iguales-a-cero" class="level2">
<h2 class="anchored" data-anchor-id="ausencia-de-anticipación-no-garantiza-leads-twfe-iguales-a-cero">Ausencia de anticipación no garantiza leads TWFE iguales a cero</h2>
<p>En la aplicación sobre hospitalización e ingresos laborales, se fijan en cero todos los CATT pretratamiento y se conservan los efectos estimados posteriores. Aun bajo esa ausencia de anticipación, las contribuciones netas pos-tratamiento a los coeficientes de ingresos alcanzan las siguientes magnitudes, expresadas aproximadamente en dólares de 2005:</p>
<div class="metric-grid">
<div class="metric-card">
<div class="metric-label">
<p>Contribución a lead −3</p>
</div>
<div class="metric-value">
<p>+441,6</p>
</div>
<div class="metric-note">
<p>contribución neta de efectos pos-tratamiento</p>
</div>
</div>
<div class="metric-card">
<div class="metric-label">
<p>Contribución a lead −2</p>
</div>
<div class="metric-value">
<p>−115,9</p>
</div>
<div class="metric-note">
<p>contribución neta de efectos pos-tratamiento</p>
</div>
</div>
</div>
<p>El ejercicio no afirma que esos números sean los verdaderos efectos previos. Demuestra algo más básico: un <em>lead</em> TWFE puede moverse por efectos que ocurren después del tratamiento. Por eso no constituye automáticamente un test limpio de anticipación o tendencias paralelas.</p>
</section>
<section id="aplicación-hospitalización-y-consecuencias-económicas" class="level2">
<h2 class="anchored" data-anchor-id="aplicación-hospitalización-y-consecuencias-económicas">Aplicación: hospitalización y consecuencias económicas</h2>
<p>La aplicación utiliza RAND HRS Longitudinal File 2022 para estudiar cómo evolucionan el gasto médico de bolsillo y los ingresos laborales alrededor de la primera hospitalización observada. Ilustra el método de Sun–Abraham con esta base alternativa. Las cohortes se definen por la ronda de encuesta en que ocurre esa hospitalización índice.</p>
<div class="quick-grid">
<div class="section-box">
<p><strong>Población inicial</strong></p>
<p>2.332 personas de 50 a 59 años al momento de la hospitalización índice.</p>
</div>
<div class="section-box">
<p><strong>Panel</strong></p>
<p>Rondas 7–11, aproximadamente 2004–2012, conservando el desbalance observado.</p>
</div>
<div class="section-box">
<p><strong>Tratamiento</strong></p>
<p>Indicador que permanece activo desde la primera hospitalización en las rondas 8, 9, 10 u 11.</p>
</div>
<div class="section-box">
<p><strong>Resultados</strong></p>
<p>Gasto médico de bolsillo e ingresos laborales, expresados aproximadamente en dólares de 2005 y con valores extremos limitados al percentil 99,95.</p>
</div>
</div>
<p>La ventana central utiliza tiempos relativos <code>−3</code>, <code>−2</code>, <code>0</code>, <code>1</code> y <code>2</code>, con <code>−1</code> como referencia. Cada paso corresponde a una ronda de encuesta, aproximadamente dos años. La muestra comparable contiene <strong>3.605 observaciones de 963 personas</strong>, con errores estándar agrupados por individuo. La especificación central incluye efectos fijos de persona y ronda, sin covariables adicionales.</p>
</section>
<section id="cohortes-control-y-soporte" class="level2">
<h2 class="anchored" data-anchor-id="cohortes-control-y-soporte">Cohortes, control y soporte</h2>
<p>La muestra analítica está definida alrededor de una hospitalización observada, por lo que no contiene un grupo nunca tratado limpio con un tiempo índice comparable. La estrategia utiliza la cohorte tratada en la ronda 11 como control y restringe la estimación a las rondas anteriores, cuando esa cohorte todavía no fue hospitalizada.</p>
<p>El soporte cambia con el tiempo relativo. Tres cohortes contribuyen al período 0, dos al período 1 y solo la cohorte 8 permite estimar el período 2. Aunque se observa a la cohorte 8 en <span class="math inline">\(\ell=3\)</span>, ese horizonte coincide con la ronda 11: la cohorte de control ya se hospitalizó. Por eso no hay una comparación no tratada para construir el estimador interaction-weighted en ese punto.</p>
</section>
<section id="twfe-frente-a-interaction-weighted" class="level2">
<h2 class="anchored" data-anchor-id="twfe-frente-a-interaction-weighted">TWFE frente a interaction-weighted</h2>
<p>Sun–Abraham estima primero efectos específicos por cohorte y tiempo relativo, utilizando como comparación a la cohorte aún no tratada. El estimador interaction-weighted —IW, ponderado por interacciones— los agrega con participaciones no negativas que suman uno entre las cohortes con soporte en cada horizonte:</p>
<p><span class="math display">\[
\widehat\nu_\ell
=\sum_{e\in h_\ell}\widehat p_{e,\ell}\,\widehat{CATT}_{e,\ell},
\qquad \widehat p_{e,\ell}\geq 0,
\qquad \sum_{e\in h_\ell}\widehat p_{e,\ell}=1.
\]</span></p>
<p>Aquí <span class="math inline">\(h_\ell\)</span> reúne las cohortes con una comparación disponible. Bajo tendencias paralelas y ausencia de anticipación, cada punto estima un promedio causal para ese mismo tiempo relativo. Por ejemplo, el gasto en el período de hospitalización combina los efectos de las cohortes 8, 9 y 10 con pesos de 0,2306, 0,1519 y 0,6175: <span class="math inline">\(0{,}2306(3.220{,}6)+0{,}1519(2.411{,}9)+0{,}6175(2.515{,}2)\approx 2.662\)</span> dólares.</p>
<p>En esta aplicación, TWFE e IW producen curvas numéricamente cercanas. Esa proximidad es un resultado empírico, no una garantía algebraica ni una equivalencia entre estimandos.</p>
<div class="table-box">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Tiempo relativo</th>
<th style="text-align: right;">Gasto TWFE</th>
<th style="text-align: right;">Gasto IW</th>
<th style="text-align: right;">Ingresos TWFE</th>
<th style="text-align: right;">Ingresos IW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">−3</td>
<td style="text-align: right;">226</td>
<td style="text-align: right;">278</td>
<td style="text-align: right;">3.294</td>
<td style="text-align: right;">2.493</td>
</tr>
<tr class="even">
<td style="text-align: right;">−2</td>
<td style="text-align: right;">511</td>
<td style="text-align: right;">474</td>
<td style="text-align: right;">−2.751</td>
<td style="text-align: right;">−3.515</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;"><strong>2.916</strong></td>
<td style="text-align: right;"><strong>2.662</strong></td>
<td style="text-align: right;"><strong>−6.318</strong></td>
<td style="text-align: right;"><strong>−7.267</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">373</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;"><strong>−12.121</strong></td>
<td style="text-align: right;"><strong>−10.632</strong></td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">483</td>
<td style="text-align: right;">198</td>
<td style="text-align: right;"><strong>−14.189</strong></td>
<td style="text-align: right;"><strong>−14.734</strong></td>
</tr>
</tbody>
</table>
</div>
<p>Las cifras están expresadas aproximadamente en dólares de 2005. La tabla compara las estimaciones; los errores estándar y la figura siguiente completan la lectura de su precisión.</p>
</section>
<section id="gasto-médico-e-ingresos-laborales" class="level2">
<h2 class="anchored" data-anchor-id="gasto-médico-e-ingresos-laborales">Gasto médico e ingresos laborales</h2>
<p>El estimador IW muestra un aumento inmediato del gasto médico de bolsillo en el período de hospitalización: <strong>2.662 dólares</strong>, con EE <strong>649</strong>. Las estimaciones posteriores son 183 y 198 dólares, ambas imprecisas.</p>
<p>Para ingresos laborales, IW estima una caída de <strong>7.267 dólares</strong> en el período 0, con EE <strong>3.237</strong>. La reducción alcanza <strong>10.632 dólares</strong> en el período 1 —EE 5.079— y <strong>14.734 dólares</strong> en el período 2 —EE 7.416—.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="did_m06_ingresos_twfe_iw.svg" class="img-fluid figure-img" alt="TWFE e interaction-weighted producen trayectorias numéricamente próximas para los ingresos laborales. Ambos muestran estimaciones previas imprecisas y caídas desde el período cero, con intervalos amplios. En el período dos, IW representa únicamente a la cohorte ocho."></p>
<figcaption>Trayectoria de ingresos laborales estimada por TWFE e interaction-weighted</figcaption>
</figure>
</div>
<div class="small-note">
<p><strong>Alcance de la trayectoria.</strong> Los efectos se refieren a las cohortes de hospitalización con soporte en esta muestra de personas de 50 a 59 años al ingreso, comparadas con quienes se hospitalizan en la ronda 11 mientras aún no recibieron el tratamiento. La caída de <strong>14.734 dólares</strong> en el período 2 corresponde exclusivamente a la cohorte 8. El aumento de las pérdidas entre horizontes combina duración desde la hospitalización y cambios en las cohortes representadas; no describe por sí solo el deterioro de una población constante.</p>
</div>
<p>La comparación no sostiene que TWFE haya fallado dramáticamente en esta muestra. Muestra que dos curvas parecidas pueden tener construcciones diferentes: IW agrega CATT cohorte-tiempo de forma explícita; TWFE puede mezclar efectos de otros momentos relativos.</p>
</section>
<section id="qué-dicen-y-qué-no-dicen-los-leads" class="level2">
<h2 class="anchored" data-anchor-id="qué-dicen-y-qué-no-dicen-los-leads">Qué dicen —y qué no dicen— los leads</h2>
<p>Los tests conjuntos de los períodos <code>−3</code> y <code>−2</code> arrojan:</p>
<div class="table-box">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Resultado</th>
<th style="text-align: right;">Test de leads TWFE</th>
<th style="text-align: right;">Test de leads IW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gasto médico de bolsillo</td>
<td style="text-align: right;">p = 0,6705</td>
<td style="text-align: right;">p = 0,8330</td>
</tr>
<tr class="even">
<td>Ingresos laborales</td>
<td style="text-align: right;">p = 0,0912</td>
<td style="text-align: right;">p = 0,2485</td>
</tr>
</tbody>
</table>
</div>
<p>Los resultados IW no muestran evidencia estadística de efectos previos en la ventana utilizada. El horizonte previo es corto y los intervalos son amplios, por lo que el no rechazo también puede reflejar poca potencia. Es un diagnóstico compatible con ausencia de anticipación, no una prueba definitiva de tendencias paralelas.</p>
<p>En TWFE, la interpretación es todavía más limitada. Un <em>lead</em> distinto de cero podría reflejar anticipación, diferencias preexistentes, contaminación pos-tratamiento u otros tiempos relativos. Un no rechazo tampoco demuestra que las comparaciones contrafactuales sean válidas.</p>
</section>
<section id="sensibilidad-con-covariables-prefijadas" class="level2">
<h2 class="anchored" data-anchor-id="sensibilidad-con-covariables-prefijadas">Sensibilidad con covariables prefijadas</h2>
<p>Como comprobación adicional, el taller incorpora edad y cobertura de Medicaid, Medicare y seguro privado, fijadas en el primer valor observado dentro de la muestra anterior a la ronda 11 e interactuadas con el tiempo calendario. El IW contemporáneo cambia de <strong>2.662 a 2.416 dólares</strong> para gasto y de <strong>−7.267 a −7.210 dólares</strong> para ingresos. Los tests conjuntos de <em>leads</em> siguen sin rechazar (<code>p = 0,565</code> y <code>p = 0,396</code>, respectivamente).</p>
<p>La estabilidad de esos puntos es informativa, pero la especificación se presenta como una sensibilidad mecánica. Permite tendencias condicionales distintas según observables prefijados; no elimina la contaminación de TWFE ni reemplaza el argumento de identificación. Una aplicación definitiva requeriría fijar esos controles dentro de una ventana pretratamiento común y limpia.</p>
</section>
<section id="qué-exige-una-dinámica-causal-interpretable" class="level2">
<h2 class="anchored" data-anchor-id="qué-exige-una-dinámica-causal-interpretable">Qué exige una dinámica causal interpretable</h2>
<p>La solución interaction-weighted reconstruye el event study a partir de cuatro decisiones:</p>
<ol type="1">
<li>definir efectos causales por cohorte y período;</li>
<li>utilizar grupos de comparación que todavía no recibieron el tratamiento;</li>
<li>verificar que cada tiempo relativo tenga soporte;</li>
<li>agregar los efectos mediante reglas explícitas y transparentes.</li>
</ol>
<p>La interpretación causal de esa trayectoria depende de tendencias paralelas entre las cohortes comparadas y de ausencia de anticipación. La agregación explícita permite conocer qué efectos se promedian; los supuestos del diseño sostienen su identificación.</p>
</section>
<section id="conclusión" class="level2">
<h2 class="anchored" data-anchor-id="conclusión">Conclusión</h2>
<p>Un event study TWFE no puede interpretarse automáticamente como una trayectoria de ATT por tiempo relativo. Bajo adopción escalonada y heterogeneidad, cada coeficiente puede mezclar cohortes y momentos distintos; incluso un <em>lead</em> puede contener efectos pos-tratamiento.</p>
<p>En la aplicación HRS, TWFE e IW son numéricamente próximos: el gasto médico aumenta en la hospitalización y los ingresos laborales caen desde el período índice. La similitud de las curvas no elimina la diferencia de estimando ni convierte los <em>leads</em> TWFE en tests limpios de pretratamiento.</p>
<p>Sun–Abraham ofrece una solución específica a la contaminación dinámica: <strong>estimar efectos por cohorte y período mediante comparaciones válidas y agregarlos después con participaciones explícitas</strong>. Cada punto adquiere así un significado causal bajo los supuestos del diseño, con un alcance determinado por las cohortes que tienen soporte en ese horizonte.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Daniel Méndez</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="../../creditos-imagenes.html">Créditos de imágenes</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>