project:
  type: website
  output-dir: _site

website:
  title: "Daniel Méndez"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Problemas de negocio"
        href: problemas-negocio.qmd
      - text: "Econometría"
        href: econometria/index.qmd
      - text: "Causalidad"
        href: causalidad/index.qmd
      - text: "Machine Learning"
        href: machine-learning/index.qmd
      - text: "Sobre mí"
        href: sobre-mi.qmd
  page-footer:
    left: "Daniel Méndez"
    right: "[Créditos de imágenes](/creditos-imagenes.qmd)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    include-in-header:
      - assets/noindex.html

lang: es

